#!/bin/sh
nginx -s quit
./configure --add-module=../../naxsi/naxsi_src/ --add-module=./src/ext/ngx_http_utm_module --add-module=./src/ext/ngx_http_av_module --add-module=./src/ext/echo-nginx-module --add-module=./src/ext/ngx_http_footer_filter_module --add-module=./src/ext/ngx_http_hello_world_module --with-debug --with-http_addition_module  --with-http_ssl_module 
make && make install
nginx 
